import React, {useState} from 'react'
import './btlsrvboard.scss'
import stoplight from '../../Assets/stoplight.svg'
import threebar from '../../Assets/threebar.svg'
import sidebar from '../../Assets/sidebar.svg'
import twodots from '../../Assets/twominidots.svg'
import manydots from '../../Assets/manydots.svg'
import blank from '../../Assets/Background.svg'

const Btlsrvboard = props => {
    return (
        <div className='btlsrvboard-comp'>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={threebar} alt=''/>
<img src={sidebar} alt=''/>
<img src={twodots} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={threebar} alt=''/>
<img src={manydots} alt=''/>
<img src={twodots} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={manydots} alt=''/>
<img src={stoplight} alt=''/>
<img src={threebar} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={manydots} alt=''/>
<img src={twodots} alt=''/>
<img src={threebar} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={twodots} alt=''/>
<img src={manydots} alt=''/>
<img src={stoplight} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={stoplight} alt=''/>
<img src={manydots} alt=''/>
<img src={twodots} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={stoplight} alt=''/>
<img src={manydots} alt=''/>
<img src={threebar} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={threebar} alt=''/>
<img src={manydots} alt=''/>
<img src={sidebar} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={sidebar} alt=''/>
<img src={threebar} alt=''/>
<img src={twodots} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={twodots} alt=''/>
<img src={stoplight} alt=''/>
<img src={threebar} alt=''/>
<img src={stoplight} alt=''/>
<img src={sidebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={stoplight} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={manydots} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={threebar} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
<img src={blank} alt=''/>
        </div>
    )
}

export default Btlsrvboard